export const styleInputMargin = 'mx-[.5em] mt-[.2em] w-[calc(100%_-_1em)]'
export const styleMinInputWidth = 'w-[16em]'
export const styleFormBgWhite = 'bg-white shadow-md'
export const styleModalFormWidth = 'w-[600px]'
export const stylePageFormWidth = 'w-[90%]'
export const styleTableTRPadding = 'p-[0.6em]'
