export const styleInputMargin = 'mx-[1em] mt-[.2em] w-[calc(100%_-_2em)]'
export const styleMinInputWidth = 'w-[16em]'
export const styleFormBgWhite = 'bg-white shadow-md'
export const styleModalFormWidth = 'w-[600px]'
export const stylePageFormWidth = 'w-[90%]'
